version: 2.1

executors:
  php-8.0:
    docker:
      image: cimg/php:8.0
  php-8.1:
    docker:
      image: cimg/php:8.1

jobs:
  test:
    parameters:

    docker:
      - image: cimg/php:<< parameters.php-version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-<< parameters.php-version >>-dependencies-lowest-{{ checksum "composer.json" }}
            - v1-<< parameters.php-version >>-dependencies-lowest-
      - run: composer update --prefer-lowest
      - save_cache:
          key: v1-<< parameters.php-version >>-dependencies-lowest-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer test
      - restore_cache:
          keys:
            - v1-<< parameters.php-version >>-dependencies-highest-{{ checksum "composer.json" }}
            - v1-<< parameters.php-version >>-dependencies-highest-
      - run: composer update
      - save_cache:
          key: v1-<< parameters.php-version >>-dependencies-highest-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              php-version: [8.0, 8.1]
