version: 2.1

executors:
  php80:
    docker:
      - image: cimg/php:8.0
  php81:
    docker:
      - image: cimg/php:8.1

jobs:
  test:
    parameters:
      php-executor:
        type: string
    executor: << parameters.php-executor >>
    steps:
      - checkout
      - run: sudo curl -fLSso /usr/local/bin/install-php-extensions https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
      - run: sudo chmod +x /usr/local/bin/install-php-extensions
      - run: sudo install-php-extensions apcu redis
      - run: echo 'apc.enable_cli=1' | sudo tee -a /etc/php.d/circleci.ini
      - restore_cache:
          keys:
            - v1-<< parameters.php-executor >>-dependencies-lowest-{{ checksum "composer.json" }}
            - v1-<< parameters.php-executor >>-dependencies-lowest-
      - run: composer update --prefer-lowest
      - save_cache:
          key: v1-<< parameters.php-executor >>-dependencies-lowest-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer test
      - restore_cache:
          keys:
            - v1-<< parameters.php-executor >>-dependencies-highest-{{ checksum "composer.json" }}
            - v1-<< parameters.php-executor >>-dependencies-highest-
      - run: composer update
      - save_cache:
          key: v1-<< parameters.php-executor >>-dependencies-highest-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              php-executor: [php80, php81]
